name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory: apis/poi/

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: 
        cd web
        dotnet build --configuration Release --no-restore
    - name: Test
      run: 
        cd tests
        dotnet test --no-restore --verbosity normal
