name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory: apis/poi/

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd web
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd tests/UnitTests
        dotnet test --no-restore --verbosity normal
    - uses: azure/docker-login@v1      
      with:
        login-server: openhackc7q85ic6acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Deploy to Docker  
      run: |
        docker build . -t openhackc7q85ic6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackc7q85ic6acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 
